// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLA7TLwCBP--6xoyq2pODvY9002bj48WM',
    appId: '1:253631505887:web:cf5a5619bd8190621c506a',
    messagingSenderId: '253631505887',
    projectId: 'tsts-3d6fc',
    authDomain: 'tsts-3d6fc.firebaseapp.com',
    storageBucket: 'tsts-3d6fc.appspot.com',
    measurementId: 'G-9BS0JTND4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2BLbNtZA_i50HDfa0JWlCpG8q8vs7-ME',
    appId: '1:253631505887:android:53718306b9f1de891c506a',
    messagingSenderId: '253631505887',
    projectId: 'tsts-3d6fc',
    storageBucket: 'tsts-3d6fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmt9OlhM4q0ns7YBDXmYFBN9rzu4OtrLE',
    appId: '1:253631505887:ios:6b0635e470fe49351c506a',
    messagingSenderId: '253631505887',
    projectId: 'tsts-3d6fc',
    storageBucket: 'tsts-3d6fc.appspot.com',
    iosClientId: '253631505887-ut1j5ebjb0247l58b2g528el70g1ohdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttertest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmt9OlhM4q0ns7YBDXmYFBN9rzu4OtrLE',
    appId: '1:253631505887:ios:21683eed5a5de6571c506a',
    messagingSenderId: '253631505887',
    projectId: 'tsts-3d6fc',
    storageBucket: 'tsts-3d6fc.appspot.com',
    iosClientId: '253631505887-clv1he2oil08jic3bg5m6iognfuenjle.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttertest.RunnerTests',
  );
}
